### ISSUE TITLE
Broken links. Updates?

### ISSUE THREAD

**Issue by rachejazz** [ILUGD/awesome-community-members-blogs#3]
Found most of them 404. How do other members (like me) drop our blogs here?

I belong to the telegram channel. Do I need to become member on GitHub?

**Comment by hellozee** [comment]
Nah, just put up a PR, regarding 404s, probably just have to remind them a bit, :)

**Comment by rachejazz** [comment]
Cool! While mine is still in a nascent stage, I'd add more after I keep a PR her :D
